spring:
  application:
    name: api_getway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: user_service
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/user/**
        - id: product_service
          uri: http://localhost:1991
          predicates:
            - Path=/api/v1/product/**
#        - id: StockTransaction
#          uri: http://localhost:9094
#          predicates:
#            - Path=/api/v1/transaction/**
#          filters:
#            - name: AuthenticationFilter
server:
  port: 1990

application:
    security:
      jwt:
        public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAugXpAWSLpr8EEfRB8Ki0CSK9WTBLV8aUGc2QoPeTgjxLgU99fBQ43Iw9AZvs+uTCtQIVaJ/ezJHueNzzyEt9j7ad4snmctJuVjWkLF/LrIHhUwUNYT7AubxUYpMS4wGOku/K4htFiAO0RdPeilJZBk/3KP2BW4jjVgbj2LoSybUSBqxNQFtMrJdYePZBg0CjzyS2W95uMV74jahCb9zAoNZd9/zLESDICUuETmrKogph7RWHBBjwiUb1O76AjmsB6QjKYn/TgqSpLydG2Mzd3YHYjfBuWG87dnF2npOrbGyDiq/WDubu+M+lbT9nFZGuCbUyfcAVTt1PNgNAxVx9ZQIDAQAB
