version: '3'
services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    networks:
      - spring
    volumes:
      - ./elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  kibana:
      container_name: kibana-Container
      image: docker.elastic.co/kibana/kibana:8.11.1
      environment:
        - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      networks:
        - spring
      depends_on:
        - elasticsearch
      ports:
        - 5602:5601
  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:8.11.1
    networks:
      - spring
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - 5044:5044
    depends_on:
      - elasticsearch
networks:
  spring: