spring:
  application:
    name: product_service

  datasource:
    jdbcUrl: jdbc:mysql://localhost:3300/product_service?autoreconnect=true
    username: root
    password: Vu123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    maximumPoolSize: 5



  flyway:
    baseline-on-migrate: true
    enabled: false
    locations: classpath:db.migration
appConfig:
  default-page-size: 10
  default-page-number: 0
logging:
  level:
    org.springframework.jdbc.core: DEBUG
    org.flywaydb.core: DEBUG
server:
  port: 1991
uploading:
  videoSaveFolder: /Volumes/Extreme SSD/Java/tasc_spring/product_service/src/main/resources/static
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
    preferIpAddress: true