spring:
  application:
    name: PRODUCT_SERVICE

  datasource:
    jdbcUrl: jdbc:mysql://localhost:3300/product_service?autoreconnect=true
    username: root
    password: Vu123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    maximumPoolSize: 5
  flyway:
    baseline-on-migrate: true
    enabled: false
    locations: classpath:db.migration
appConfig:
  default-page-size: 10
  default-page-number: 0
logging:
  level:
    org.springframework.jdbc.core: DEBUG
    org.flywaydb.core: DEBUG
server:
  port: 1991
uploading:
  videoSaveFolder: /Volumes/Extreme SSD/Java/tasc_spring/product_service/src/main/resources/static
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    instance:
    preferIpAddress: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

cloudinary:
  api_secret: Zs2Zcw-7Pf3B6EWRiUUkV1tRYWA
  cloud_name: dlqv9yphm
  api_key: 655111386821477
  folderName:  product
